name: Vite CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Build the Vite project
      - name: Build Project
        run: npm run build

      # 5. Build Docker Image
      - name: Build Docker Image
        run: docker build -t vite .

      # 6. Save Docker Image as Artifact
      - name: Save Docker Image
        run: docker save vite | gzip > vite.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vite-docker-image
          path: vite.tar.gz
